### ISSUE TITLE
将页面放入项目里面运行，提示"ReferenceError: IScroll is not defined"

### ISSUE THREAD

**Issue by chuliul** [gyfeng1003/vue-table-fixed#1]
![image](https://user-images.githubusercontent.com/37426130/115329272-aa6f1280-a1c4-11eb-9ce2-6b5d346d4880.png)

**Comment by gyfeng1003** [comment]
iscroll-probe.js文件里面有Iscroll变量，iscroll-probe.js引入了么




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gyfeng1003/vue-table-fixed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月20日(星期二) 上午10:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[gyfeng1003/vue-table-fixed] 将页面放入项目里面运行，提示"ReferenceError: IScroll is not defined" (#1)

**Comment by chuliul** [comment]
![image](https://user-images.githubusercontent.com/37426130/115331618-cd9bc100-a1c8-11eb-95a4-22d895a10483.png)
![image](https://user-images.githubusercontent.com/37426130/115331672-e7d59f00-a1c8-11eb-920d-35b35af3f96b.png)

引入啦，是将您的3个文件复制下来的，没有修改里面的东西。

**Comment by gyfeng1003** [comment]
试下window.IScroll？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gyfeng1003/vue-table-fixed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月20日(星期二) 中午11:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gyfeng1003/vue-table-fixed] 将页面放入项目里面运行，提示"ReferenceError: IScroll is not defined" (#1)





 

 
 
引入啦，是将您的3个文件复制下来的，没有修改里面的东西。

**Comment by chuliul** [comment]
![image](https://user-images.githubusercontent.com/37426130/115332328-2f105f80-a1ca-11eb-9749-9668f24d53a6.png)

已找到其他解决方法，原文件里这里的名字为‘iScollProbe’，修改为'IScroll'就可以使用了。

**Comment by gyfeng1003** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gyfeng1003/vue-table-fixed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月20日(星期二) 中午11:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gyfeng1003/vue-table-fixed] 将页面放入项目里面运行，提示"ReferenceError: IScroll is not defined" (#1)





 

 
已找到其他解决方法，原文件里这里的名字为‘iScollProbe’，修改为'IScroll'就可以使用了。

**Comment by chuliul** [comment]
目前这个只实现了第一列固定吗？

**Comment by gyfeng1003** [comment]
代码里搜一下:class="{'cross': index == 0 &amp;&amp; i == 0}"和:class="{'cols': yKey == xField[0]}"，改变cross、cols显示的条件控制



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gyfeng1003/vue-table-fixed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月20日(星期二) 下午2:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gyfeng1003/vue-table-fixed] 将页面放入项目里面运行，提示"ReferenceError: IScroll is not defined" (#1)





 
目前这个只实现了第一列固定吗？

**Comment by gyfeng1003** [comment]
已解决
